name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Start app
        run: |
          npm run dev &
          npx wait-on http://localhost:5173

      - name: Run Cypress
        run: npx cypress run